MARKER SNP
ALLELE A1 A2
EFFECT BETA
SCHEME STDERR

STDERRLABEL SE
AVERAGEFREQ ON
MINMAXFREQ ON
FREQLABEL MAF
CUSTOMVARIABLE NMISS
GENOMICCONTROL ON
PROCESS hdl_metal_file1.txt
PROCESS hdl_metal_file2.txt
OUTFILE hdl_metal_results .txt
ANALYZE HETEROGENEITY
CLEAR
